env:
  browser: true
  commonjs: true
  es2021: true
  jest: true
extends: 
  - standard
parserOptions:
  ecmaVersion: latest
plugins: 
  - sonarjs
rules:
  sonarjs/cognitive-complexity: ["error", 15]
  sonarjs/no-all-duplicated-branches: "error"
  sonarjs/no-element-overwrite: "error"
  sonarjs/no-extra-arguments: "error"
  sonarjs/no-identical-conditions: "error"
  sonarjs/no-identical-expressions: "error"
  sonarjs/no-one-iteration-loop: "error"
  sonarjs/no-use-of-empty-return-value: "error"