services:
  server:
    build:
      dockerfile: Dockerfile.app
      context: .
      target: ${TARGET}
    volumes:
      - ./db:/usr/src/app/db
      - ./src:/usr/src/app/src
    ports:
      - 3000:3000
    environment:
      - HUSKY=0
      - DATABASE_URL=file:../db/minitwit.db
    env_file:
      - path: ./.env
        required: true
  api:
    build:
      dockerfile: Dockerfile.api
      context: .
      target: ${TARGET}
    volumes:
      - ./db:/usr/src/app/db
      - ./src:/usr/src/app/src
    ports:
      - 3001:3000
    environment:
      - HUSKY=0
      - DATABASE_URL=file:../db/minitwit.db
    env_file:
      - path: ./.env
        required: true
