services:
  server:
    container_name: maxitwitserver
    build:
      dockerfile: Dockerfile.app
      context: .
      target: ${TARGET}
    volumes:
      - ./src:/usr/app/src
    ports:
      - 3000:3000
    environment:
      - HUSKY=0
    links:
      - fluentd
    logging:
      driver: "fluentd"
      options:
        fluentd-address: localhost:24224
        tag: frontend.access
        fluentd-async: "true"
    env_file: .env
    depends_on:
      - postgres
      - fluentd
    restart: always

  api:
    container_name: maxitwitapi
    build:
      dockerfile: Dockerfile.api
      context: .
      target: ${TARGET}
    volumes:
      - ./src:/usr/app/src
    ports:
      - 3001:3001
    environment:
      - HUSKY=0
    links:
      - fluentd
    logging:
      driver: "fluentd"
      options:
        fluentd-address: localhost:24224
        tag: api.access
        fluentd-async: "true"

    env_file: .env
    depends_on:
      - postgres
      - fluentd
    restart: always

  prometheus:
    image: prom/prometheus
    container_name: prometheus
    volumes:
      - ./conf/prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - '9090:9090'

  grafana:
    image: grafana/grafana:10.2.4
    ports:
      - '3002:3000'
    volumes:
      - grafana_data:/var/lib/grafana

  postgres:
    image: postgres:latest
    container_name: postgres
    environment:
      POSTGRES_USER: pguser
      POSTGRES_PASSWORD: pgpassword
      POSTGRES_DB: localdb
      PGPORT: 9998
    ports:
      - 9998:9998

  fluentd:
    container_name: fluentd
    user: root
    build:
      dockerfile: Dockerfile.fluentd
    volumes:
      - ./conf/fluentd.conf:/fluentd/etc/fluent.conf
    logging:
      driver: "local"
    ports:
      - 24224:24224
      - 24224:24224/udp

volumes:
  grafana_data:
