FROM python:3.12.1-alpine

RUN mkdir /minitwit-tests

WORKDIR .

COPY conftest.py /minitwit-tests/
COPY minitwit_test.py /minitwit-tests/
COPY test_requirements.txt /minitwit-tests/

WORKDIR /minitwit-tests

RUN pip install -r test_requirements.txt

EXPOSE 3000

ENTRYPOINT ["pytest", "minitwit_test.py", "--force", "--container"]