FROM node:latest

RUN apt-get update && apt-get install -y \
    pandoc \
    texlive-latex-base \
    texlive-fonts-recommended \
    texlive-fonts-extra \
    texlive-latex-extra

RUN npm install -g mermaid-filter

WORKDIR /data

COPY ./report /data


CMD pandoc -s -N -o report.pdf \
    -V colorlinks=true \
    -V linkcolor=blue \
    --pdf-engine=pdflatex \
    -V urlcolor=blue \
    --filter mermaid-filter \
    ./report.md