FROM python:3.7-alpine

RUN mkdir /minitwit-tests

COPY minitwit_test.py /minitwit-tests/
COPY src/api/tmp/requirements/requirements.txt /minitwit-tests/

WORKDIR /minitwit-tests

RUN pip install -r requirements.txt

EXPOSE 3001

ENTRYPOINT ["pytest", "-s", "minitwit_tests.py"]