FROM python:3.7-alpine

RUN mkdir /minitwit-tests

WORKDIR .

COPY minitwit_test.py /minitwit-tests/
COPY requirements.txt /minitwit-tests/

WORKDIR /minitwit-tests

RUN pip install -r requirements.txt

EXPOSE 3000

ENTRYPOINT ["pytest", "-s", "minitwit_test.py"]