# Description: Docker Compose file for running tests
# This file is used in the CI/CD pipeline to run tests on the application
services:
  test_db:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ${CICD_DB_PASSWORD}
      POSTGRES_DB: testdb
      PGPORT: 9999
    ports:
      - 9999:9999
    networks:
      - main

  test_server:
    container_name: test_server
    build:
      dockerfile: Dockerfile.app
      context: .
      target: test
    ports:
      - 3000:3000
    networks:
      - main
    depends_on:
      - test_db
    environment:
      - HUSKY=0
      - DATABASE_URL=postgresql://postgres:${CICD_DB_PASSWORD}@test_db:9999/testdb
      - SESSION_SECRET=secret
    restart: always

  test_api:
    container_name: test_api
    build:
      dockerfile: Dockerfile.api
      context: .
      target: test
    ports:
      - 3001:3001
    networks:
      - main
    depends_on:
      - test_db
    environment:
      - HUSKY=0
      - DATABASE_URL=postgresql://postgres:${CICD_DB_PASSWORD}@test_db:9999/testdb
      - SESSION_SECRET=secret
    restart: always

networks:
  main:
    name: maxitwit-test
