services:
  maxitwitserver:
    container_name: maxitwitserver
    build:
      dockerfile: Dockerfile.app
      context: .
      target: test
    ports:
      - 3000:3000
    networks:
      - main
    environment:
      - HUSKY=0
      - DATABASE_URL=file:../db/minitwit.db
      - SESSION_SECRET=secret

  maxitwitapi:
    container_name: maxitwitapi
    build:
      dockerfile: Dockerfile.api
      context: .
      target: test
    ports:
      - 3001:3001
    networks:
      - main
    environment:
      - HUSKY=0
      - DATABASE_URL=file:../db/minitwit.db
      - SESSION_SECRET=secret

networks:
  main:
    name: maxitwit-test
