services:
  maxitwitserver:
    container_name: maxitwitserver
    build:
      dockerfile: Dockerfile.app
      context: .
      target: test
    ports:
      - 3000:3000
    networks:
      - main
    environment:
      - HUSKY=0
      - DATABASE_URL=file:../db/minitwit.db
    env_file: .env

  maxitwitapi:
    container_name: maxitwitapi
    build:
      dockerfile: Dockerfile.api
      context: .
      target: test
    ports:
      - 3001:3001
    networks:
      - main
    environment:
      - HUSKY=0
      - DATABASE_URL=file:../db/minitwit.db
    env_file: .env

networks:
  main:
    name: maxitwit-test
