services:
  test_db:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: testdb
    ports:
      - 5432:5432
    networks:
      - main

  test_server:
    container_name: test_server
    build:
      dockerfile: Dockerfile.app
      context: .
      target: test
    ports:
      - 3000:3000
    networks:
      - main
    depends_on:
      - test_db
    environment:
      - HUSKY=0
      - DATABASE_URL=postgresql://postgres:postgres@test_db:5432/testdb
      - SESSION_SECRET=secret
    restart: always

  test_api:
    container_name: test_api
    build:
      dockerfile: Dockerfile.api
      context: .
      target: test
    ports:
      - 3001:3001
    networks:
      - main
    depends_on:
      - test_db
    environment:
      - HUSKY=0
      - DATABASE_URL=postgresql://postgres:postgres@test_db:5432/testdb
      - SESSION_SECRET=secret
    restart: always

  test_UI:
    container_name: test_UI
    build:
      dockerfile: Dockerfile.api
      context: .
      target: test
    ports:
      - 3002:3002
    networks:
      - main
    depends_on:
      - test_db
    environment:
      - HUSKY=0
      - DATABASE_URL=postgresql://postgres:postgres@test_db:5432/testdb
      - SESSION_SECRET=secret
    restart: always

networks:
  main:
    name: maxitwit-test
