services:
  maxitwitserver:
    container_name: maxitwitserver
    build:
      dockerfile: Dockerfile.app
      context: .
      target: test
    ports:
      - 3000:3000
    networks:
      - maxitwit-test
    environment:
      - HUSKY=0
      - DATABASE_URL=file:../db/minitwit.db
    env_file: .env

  maxitwitapi:
    container_name: maxitwitapi
    build:
      dockerfile: Dockerfile.api
      context: .
      target: test
    ports:
      - 3001:3001
    networks:
      - maxitwit-test
    environment:
      - HUSKY=0
      - DATABASE_URL=file:../db/minitwit.db
    env_file: .env

  # test:
  #   container_name: test_container
  #   build:
  #     dockerfile: Dockerfile.test
  #     context: .
  #   networks:
  #     - maxitwit-test
  #   depends_on:
  #     - maxitwitserver
  #     - maxitwitapi

networks:
  maxitwit-test:
    name: maxitwit-test
