services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: testdb
    ports:
      - 5432:5432
    networks:
      - main

  maxitwitserver:
    container_name: maxitwitserver
    build:
      dockerfile: Dockerfile.app
      context: .
      target: test
    ports:
      - 3000:3000
    networks:
      - main
    depends_on:
      - postgres
    environment:
      - HUSKY=0
      - DATABASE_URL=postgresql://postgres:postgres@postgres:5432/testdb
      - SESSION_SECRET=secret

  maxitwitapi:
    container_name: maxitwitapi
    build:
      dockerfile: Dockerfile.api
      context: .
      target: test
    ports:
      - 3001:3001
    networks:
      - main
    depends_on:
      - postgres
    environment:
      - HUSKY=0
      - DATABASE_URL=postgresql://postgres:postgres@postgres:5432/testdb
      - SESSION_SECRET=secret

networks:
  main:
    name: maxitwit-test
