services:

  server:
    image: ${DOCKER_USERNAME}/maxitwitserver
    ports:
      - 3000:3000
    networks:
      - maxitwit-network
    environment:
      - HUSKY=0
      - DATABASE_URL=${DATABASE_URL}
      - SESSION_SECRET=${SESSION_SECRET}
    restart: always

  api:
    image: ${DOCKER_USERNAME}/maxitwitapi
    ports:
      - 3001:3001
    networks:
      - maxitwit-network
    environment:
      - HUSKY=0
      - DATABASE_URL=${DATABASE_URL}
      - SESSION_SECRET=${SESSION_SECRET}
    restart: always


  prometheus:
    image: prom/prometheus
    container_name: prometheus
    volumes:
      - ../prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    networks:
      - maxitwit-network
    restart: always

  grafana:
    image: grafana/grafana:10.2.4
    ports:
      - "3002:3000"
    volumes:
      - grafana_data:/var/lib/grafana
    networks:
      - maxitwit-network
    restart: always

networks:
  maxitwit-network:
    name: maxitwit-network

volumes:
  grafana_data: