services:

  server:
    image: ${DOCKER_USERNAME}/maxitwitserver
    ports:
      - 3000:3000
    networks:
      - maxitwit
    environment:
      - HUSKY=0
      - DATABASE_URL=${DATABASE_URL}
      - SESSION_SECRET=${SESSION_SECRET}
    restart: always

  api:
    image: ${DOCKER_USERNAME}/maxitwitapi
    ports:
      - 3001:3001
    networks:
      - maxitwit
    environment:
      - HUSKY=0
      - DATABASE_URL=${DATABASE_URL}
      - SESSION_SECRET=${SESSION_SECRET}
    restart: always

networks:
  maxitwit:
    name: maxitwit
