---
name: Continuous Deployment

on:
  push:
    # Run workflow every time something is pushed to release
    branches:
      - release
  # allow manual triggers for now too
  workflow_dispatch:
    manual: true

# Remember to set the following secrets in your repository's settings:
# https://github.com/your_username/itu-minitwit-ci/settings/secrets/actions
# DOCKER_USERNAME
# DOCKER_PASSWORD
# SSH_USER
# SSH_KEY
# SSH_HOST

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build and push maxitwit server
        uses: docker/build-push-action@v2
        with:
          context: .
          target: "production"
          file: ./Dockerfile.app
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/maxitwitserver:latest
          cache-from: type=registry,ref=${{ secrets.DOCKER_USERNAME }}/maxitwitserver:webbuildcache
          cache-to: type=registry,ref=${{ secrets.DOCKER_USERNAME }}/maxitwitserver:webbuildcache,mode=max
      
      - name: Build and push minitwit api
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile.api
          target: "production"
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/maxitwitapi:latest
          cache-from: type=registry,ref=${{ secrets.DOCKER_USERNAME }}/maxitwitapi:webbuildcache
          cache-to: type=registry,ref=${{ secrets.DOCKER_USERNAME }}/maxitwitapi:webbuildcache,mode=max

      - name: Test maxitwit
        run: |
          docker build -t $DOCKER_USERNAME/maxitwittest -f Dockerfile.test .
          yes 2>/dev/null | docker compose up -d
          docker run --rm --network=itu-minitwit-network $DOCKER_USERNAME/maxitwittest
        env:
          TARGET: production
          SESSION_SECRET: ${{ secrets.SESSION_SECRET }}
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}

      - name: Configure SSH
        run: |
          mkdir -p ~/.ssh/
          echo "$SSH_KEY" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
        env:
          SSH_KEY: ${{ secrets.SSH_KEY }}
          SESSION_SECRET: ${{ secrets.SESSION_SECRET }}