name: Build docs

on: push

jobs:
  convert_via_pandoc:
    runs-on: ubuntu-22.04
    steps:
      - uses: docker://pandoc/core:2.9
        with:
          args: "./report/report.md -o ./report/build/report.pdf --pdf-engine=xelatex" # gets appended to pandoc command