name: Convert Markdown to PDF

on:
  push:
    branches:
      - feature/report

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Install Pandoc
      run: |
        sudo apt-get update
        sudo apt-get install -y pandoc

    - name: Convert Markdown to PDF
      run: |
        cd report && pandoc report.md -o ./build/report.pdf
      working-directory: ${{ github.workspace }}