name: Build documentation

on:
    push:
        branches:
            - feature/report
    

jobs:
  convert_via_pandoc:
    runs-on: ubuntu-22.04
    steps:
        - run: cd 
        - uses: docker://pandoc/core:2.9
        with:
          args: "--help" # gets appended to pandoc command