name: Build report

on:
  push:
    branches:
      - feature/report
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Install Pandoc
      run: |
        sudo apt-get update
        sudo apt-get install -y pandoc
        sudo apt-get install texlive-latex-base

    - name: Convert Markdown to PDF
      run: |
        cd report && pandoc report.md -o ./build/report.pdf --pdf-engine=xelatex
      working-directory: ${{ github.workspace }}